language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: bD78ANqVhYyLlbmUVrijz0qDqN7CK8vSjFxXgmJEh2ONpQmTI66K9Q2capEIfMLQQufNjjv1HVKlaW5gfqn61xIkWSLQXi6v6veweVQ2kl9859PddyHQKcQhElxN5ViWW61vRYAUI4YFUiTUsSRIwPbp3R9yeeZ6JimXuGA9WQ8=
  - secure: gwSriWt2T4geMZVr5k7UBOBtrUHMUI+UhzI4J+C2ERZ7w8cAtEf/6T1M1qhx+v1Rt237VKQ769VF8kqoHZ3VEi5rkkaNUZQKwwivJ24G7Mtt4YeUcMCqAyQlcj410JZC7BLqBcvdei7+Oz5VXIfXAn09CI1g9UJORTG0Bt5OeLE=
